# Generated by Django 2.2.2 on 2019-06-06 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('identificador_origen', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataSourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DataStorage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('boveda_path', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=200)),
                ('max_quantity', models.CharField(max_length=200)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.DataSource')),
                ('data_storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.DataStorage')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exit_code', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=200)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=200)),
                ('ip', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('host_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.HostType')),
            ],
        ),
        migrations.AddField(
            model_name='datastorage',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.Host'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='data_source_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.DataSourceType'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backups.Host'),
        ),
    ]
