# Generated by Django 2.2.2 on 2019-06-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='schedule',
            new_name='nombre',
        ),
        migrations.AddField(
            model_name='task',
            name='dia_mes',
            field=models.CharField(default='*', max_length=5),
        ),
        migrations.AddField(
            model_name='task',
            name='dia_semana',
            field=models.CharField(default='*', max_length=5),
        ),
        migrations.AddField(
            model_name='task',
            name='hora',
            field=models.CharField(default='*', max_length=5),
        ),
        migrations.AddField(
            model_name='task',
            name='mes',
            field=models.CharField(default='*', max_length=5),
        ),
        migrations.AddField(
            model_name='task',
            name='minuto',
            field=models.CharField(default='*', max_length=5),
        ),
    ]
