# Generated by Django 2.2.2 on 2019-06-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0002_auto_20190606_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dia_mes',
            field=models.CharField(default='*/*', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='dia_semana',
            field=models.CharField(default='*/*', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='hora',
            field=models.CharField(default='*/*', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_quantity',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='mes',
            field=models.CharField(default='*/*', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='minuto',
            field=models.CharField(default='*/*', max_length=5),
        ),
    ]
