# Generated by Django 2.2.2 on 2019-06-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0003_auto_20190606_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='port',
            field=models.IntegerField(default=3306),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_port',
            field=models.IntegerField(default=22),
        ),
    ]
