# Generated by Django 2.2.2 on 2019-06-10 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0004_auto_20190606_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='backup_name',
            field=models.CharField(default='test_backup', max_length=200),
        ),
        migrations.AddField(
            model_name='log',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
