# Generated by Django 2.2.2 on 2019-06-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0006_auto_20190610_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dia_mes',
            field=models.CharField(default='*', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='dia_semana',
            field=models.CharField(default='*', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='hora',
            field=models.CharField(default='*', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='mes',
            field=models.CharField(default='*', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='minuto',
            field=models.CharField(default='*', max_length=5),
        ),
        migrations.AlterField(
            model_name='task',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
