# Generated by Django 2.2.2 on 2019-06-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0007_auto_20190619_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastorage',
            name='password',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='datastorage',
            name='user',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
