# Generated by Django 2.2.2 on 2019-06-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backups', '0008_auto_20190619_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='max_retry',
            field=models.IntegerField(default=5),
        ),
    ]
